version: '3.7'

services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

volumes:
  postgresdata:
