# Generated by Django 3.0 on 2022-07-01 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InfoClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_org', models.IntegerField(db_index=True, null=True)),
                ('summ', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('service', models.CharField(max_length=255)),
                ('fraud_score', models.FloatField(null=True)),
                ('service_class', models.IntegerField(null=True)),
                ('service_name', models.CharField(max_length=255, null=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_client_orglist', to='api.InfoClient')),
                ('name_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='name_org_orglist', to='api.ClientOrg')),
            ],
        ),
        migrations.AddConstraint(
            model_name='infoclient',
            constraint=models.UniqueConstraint(fields=('client_name',), name='unique_client_name'),
        ),
        migrations.AddField(
            model_name='clientorg',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_name_clientorg', to='api.InfoClient'),
        ),
        migrations.AddConstraint(
            model_name='organisationlist',
            constraint=models.UniqueConstraint(fields=('num_org', 'name_org'), name='name of constraint'),
        ),
    ]
